#ifndef CONFIG_H
#define CONFIG_H

#include "driver/gpio.h"

/* FreeRTOS */
#define MOTOR_TASK_STACK_SIZE           4096
#define MOTOR_TASK_PRIORITY             5

#define COMM_TASK_STACK_SIZE            3072
#define COMM_TASK_PRIORITY              4

/* Fork lift stepper motor (BIGTREETECH TMC2209 V1.1, STEP/DIR mode) */
#define STEPPER_MOTOR_STEP_GPIO           GPIO_NUM_4
#define STEPPER_MOTOR_DIR_GPIO            GPIO_NUM_5
#define STEPPER_MOTOR_ENABLE_GPIO         GPIO_NUM_6
#define STEPPER_MOTOR_LOWER_LIMIT_GPIO    GPIO_NUM_7
#define STEPPER_MOTOR_ENABLE_ACTIVE_LEVEL 0
#define STEPPER_MOTOR_LOWER_LIMIT_ACTIVE_LEVEL 1
#define STEPPER_MOTOR_EXTEND_DIR_LEVEL    1

#define STEPPER_MOTOR_TIMER_RESOLUTION_HZ 1000000U
#define STEPPER_MOTOR_STEP_PULSE_HIGH_US  5U
#define STEPPER_MOTOR_PROFILE_PERIOD_MS   10U
#define STEPPER_MOTOR_TASK_STACK_SIZE     3072U
#define STEPPER_MOTOR_TASK_PRIORITY       5U

#define STEPPER_MOTOR_START_RATE_SPS      100U
#define STEPPER_MOTOR_DEFAULT_RATE_SPS    500U
#define STEPPER_MOTOR_DEFAULT_ACCEL_SPS2  250U
#define STEPPER_MOTOR_DEFAULT_MOVE_STEPS  1600U
#define STEPPER_MOTOR_HOMING_RATE_SPS     1000U
#define STEPPER_MOTOR_HOMING_ACCEL_SPS2   300U
#define STEPPER_MOTOR_HOMING_MAX_STEPS    300000U
#define STEPPER_MOTOR_HOME_BACKOFF_DELAY_MS 500U
#define STEPPER_MOTOR_HOME_BACKOFF_STEPS  1600U
#define STEPPER_MOTOR_HOME_BACKOFF_RATE_SPS 500U
#define STEPPER_MOTOR_HOME_BACKOFF_ACCEL_SPS2 300U
#define STEPPER_MOTOR_LIMIT_DEBOUNCE_MS   20U

#define STEPPER_MOTOR_MIN_RATE_SPS        20U
#define STEPPER_MOTOR_MAX_RATE_SPS        5000U
#define STEPPER_MOTOR_MAX_ACCEL_SPS2      20000U

/*
 * Keep disabled by default. Enable only for a wheel-off/load-free bench test.
 * The normal firmware never moves the lift automatically at boot.
 */
#define STEPPER_MOTOR_STARTUP_TEST_ENABLED 0
#define STEPPER_MOTOR_STARTUP_HOME_ENABLED 1
#define STEPPER_MOTOR_STARTUP_TEST_STEPS   500U
#define STEPPER_MOTOR_STARTUP_TEST_RATE_SPS 100U

/* Jetson UART */
#define JETSON_UART_PORT                UART_NUM_1
#define JETSON_UART_TX_GPIO             GPIO_NUM_17
#define JETSON_UART_RX_GPIO             GPIO_NUM_18
#define JETSON_UART_BAUD_RATE           115200
#define JETSON_UART_RX_BUFFER_SIZE      256
#define JETSON_UART_TX_BUFFER_SIZE      256
#define JETSON_UART_FRAME_MAX_LENGTH    96

/* Tele-operation safety limits */
#define TELEOP_WATCHDOG_TIMEOUT_MS      500U
#define TELEOP_MAX_DRIVE_PERCENT        60
#define TELEOP_STEERING_CENTER_CDEG     10000U
#define TELEOP_STEERING_MIN_CDEG        8500U
#define TELEOP_STEERING_MAX_CDEG        11500U

/* I2C */
#define I2C_SDA_GPIO                    GPIO_NUM_8
#define I2C_SCL_GPIO                    GPIO_NUM_9
#define I2C_FREQUENCY_HZ                100000

/* Servo PCA9685 */
#define SERVO_PCA9685_ADDRESS           0x60
#define SERVO_PCA9685_FREQUENCY_HZ      50.0f
#define SERVO_PCA9685_CHANNEL           0

/* MG996R */
#define SERVO_MIN_ANGLE_DEG             30.0f
#define SERVO_MAX_ANGLE_DEG             150.0f

#define SERVO_MIN_PULSE_US              1000U
#define SERVO_CENTER_PULSE_US           1500U
#define SERVO_MAX_PULSE_US              2000U

/* Waveshare Motor Driver HAT */
#define MOTOR_HAT_PCA9685_ADDRESS       0x40
#define MOTOR_HAT_PWM_FREQUENCY_HZ      1000.0f

/* Motor B: MB1 / MB2 */
#define MOTOR_B_PWMB_CHANNEL            5
#define MOTOR_B_BIN1_CHANNEL            3
#define MOTOR_B_BIN2_CHANNEL            4

/* Mechanical steering limits */
#define DRIVE_REAR_STEER_CENTER_ANGLE_DEG       100.0f
#define DRIVE_REAR_STEER_RIGHT_TURN_ANGLE_DEG   70.0f
#define DRIVE_REAR_STEER_LEFT_TURN_ANGLE_DEG    130.0f

#endif
